import { Public_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import TopHeader from "@/components/TopHeader";
import LayoutWrapper from "@/components/LayoutWrapper";

const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-public-sans",
});

export const metadata = {
  title: "Dating Website",
  description: "Generated by create next app",
  icons: {
    icon: "/images/fevicon.png",
    apple: "/images/fevicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${publicSans.variable} antialiased`}>
        <LayoutWrapper>{children}</LayoutWrapper>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
